### ISSUE TITLE
How to remove name of the collection from the main menu

### ISSUE THREAD

**Issue by joanfercal** [schmurtzm/Miyoo-Mini-Collection-Switcher#1]
On launch.sh I'm able to disable the name change of the collection by commenting line 177

sed -i "/\"1\":/c \"1\": \"${CollecShortName}\"," "/mnt/SDCARD/miyoo/app/lang/$CurrentLang"

But the text "== Main ==" still appears under the Favorites Icon, is there a way to completely remove the text?

Awesome work by the way.

Thanks in advance!

**Comment by schmurtzm** [comment]
Sorry for my late answer 😅 
It is due to the fact that the language file have been modified. 

You can edit manually `/mnt/SDCARD/miyoo/app/lang/en.lang` (section "1":) or you can restore it from the Onion installation package, the path in the archive   :  `\.tmp_update\.data\Core\miyoo\app\lang\en.lang`

**Comment by joanfercal** [comment]
Thank you for your help, this worked perfectly!
